server:
  port: 8180
  forward-headers-strategy: framework
spring:
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST:database}:${DB_PORT:5432}/tinder
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root}
  main:
    web-application-type: reactive
jwt:
  secret: popopo
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: '*'