server:
  port: 8180
  forward-headers-strategy: framework
spring:
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST:database}:${DB_PORT:5432}/tinder
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root}
  main:
    web-application-type: reactive
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: '*'

resilience4j.circuitbreaker:
  instances:
    auth-service-cb:
      registerHealthIndicator: true
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: TIME_BASED

resilience4j.timelimiter:
  instances:
    auth-service-cb:
      timeoutDuration: 5s
      cancelRunningFuture: true